POST http://127.0.0.1:3000/recipes HTTP/1.1
content-type: application/json

{
    "name": "Omelette",
    "ingredients": ["Eggs", "Cheese", "Milk"],
    "steps": ["Do something", "do another thing"]
}